### ISSUE TITLE
OSError: SavedModel file does not exist at: /home/hp/miniconda3/envs/gleams/gleams/data/gleams_82c0124b.hdf5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by chinmayaNK22** [bittremieux/GLEAMS#5]
I was trying to execute gleams embed as it is provided in your instructions. However, I am facing the below OSError saying that the saved model in .pbtxt or .pb format is not present in the said path.

```
**2022-12-03 15:10:00,264 INFO [gleams/MainProcess] gleams.cli_embed : GLEAMS version 0.4.dev1+g8831ad6
2022-12-03 15:10:00,282 DEBUG [gleams/MainProcess] encoder.__init__ : Read the reference spectra
2022-12-03 15:10:00,907 DEBUG [gleams/MainProcess] encoder.__init__ : Select 500 valid reference spectra
2022-12-03 15:10:03,207 DEBUG [gleams/MainProcess] nn.embed : Load the stored GLEAMS neural network
2022-12-03 15:10:04,047 DEBUG [gleams/MainProcess] embedder.__init__ : Running the embedder model on 1 GPU(s)
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/gleams/bin/gleams", line 8, in <module>
    sys.exit(gleams())
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/gleams/gleams.py", line 97, in cli_embed
    nn.embed(metadata_filename, config.model_filename, f'{embed_name}.npy',
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/gleams/nn/nn.py", line 163, in embed
    emb.load()
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/gleams/nn/embedder.py", line 158, in load
    self.siamese_model = keras.models.load_model(self.filename)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: /home/hp/miniconda3/envs/gleams/gleams/data/gleams_82c0124b.hdf5/{saved_model.pbtxt|saved_model.pb}
```
The error is because any package is missing in the conda environment where gleams has been installed?

--
Chinmaya

**Comment by bittremieux** [comment]
Apologies for the long delay in responding, I missed this issue.

It seems that there's something wrong with the stored model weights. To verify that this is indeed the problem, can you (i) check whether there is indeed a file `/home/hp/miniconda3/envs/gleams/gleams/data/gleams_82c0124b.hdf5` or not, and (ii) in case this file doesn't exist, manually downloading and placing the [gleams_82c0124b.hdf5](https://github.com/bittremieux/GLEAMS/blob/master/data/gleams_82c0124b.hdf5) file in that location to see if it fixes the issue?

**Comment by chinmayaNK22** [comment]
There was a gleams_82c0124b.hdf5 file and it was replaced with the new one which you have shared now. However, the embed function is not executing properly. Below is the new error I am facing now.

```
2023-03-09 11:18:50,004 INFO [gleams/MainProcess] gleams.cli_embed : GLEAMS version 0.4.dev1+g8831ad6
2023-03-09 11:18:50,023 DEBUG [gleams/MainProcess] encoder.__init__ : Read the reference spectra
2023-03-09 11:18:50,643 DEBUG [gleams/MainProcess] encoder.__init__ : Select 500 valid reference spectra
2023-03-09 11:18:52,940 DEBUG [gleams/MainProcess] nn.embed : Load the stored GLEAMS neural network
2023-03-09 11:18:53,774 DEBUG [gleams/MainProcess] embedder.__init__ : Running the embedder model on 1 GPU(s)
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/gleams/bin/gleams", line 8, in <module>
    sys.exit(gleams())
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/gleams/gleams.py", line 97, in cli_embed
    nn.embed(metadata_filename, config.model_filename, f'{embed_name}.npy',
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/gleams/nn/nn.py", line 163, in embed
    emb.load()
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/gleams/nn/embedder.py", line 158, in load
    self.siamese_model = keras.models.load_model(self.filename)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/hp/miniconda3/envs/gleams/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 176, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by bittremieux** [comment]
Hmm, this might be due to [dependency issues between Keras and h5py](https://github.com/tensorflow/tensorflow/issues/44467). Can you try to do `pip uninstall hy5py && pip install h5py==2.10.0` and see if it works after that?

**Comment by chinmayaNK22** [comment]
Finally, It's working. Thank you for your support.

**Comment by petercim** [comment]
I'm hitting the same error (`OSError: SavedModel file does not exist`). Reinstalling hy5py didn't help. Any tips for what worked for others?

**Comment by petercim** [comment]
> I'm hitting the same error (`OSError: SavedModel file does not exist`). Reinstalling hy5py didn't help. Any tips for what worked for others?

OK, I was able to fix this by downloading hdf5 file from [this](https://massive.ucsd.edu/ProteoSAFe/dataset_files.jsp?task=fdbaf48e52974500a0912a0db9b936c3#%7B%22table_sort_history%22%3A%22main.collection_asc%22%7D) location.

**Comment by bittremieux** [comment]
Someone has been hitting my repositories with an automated process recently, due to which my free Git LFS traffic provided by GitHub has been exhausted. Unfortunately this results in a missing weights file when following the installation instructions. Manually downloading the weights file is a temporary workaround until my Git LFS traffic resets in a few weeks.
